on:
  workflow_call:
    secrets:
      AUTH_GITHUB_TOKEN:
        required: true
      NUGET_GITHUB_USERNAME:
        required: true
      AUTH_TOKEN:
        required: true

jobs:
  codeql:
    permissions:
      security-events: write
    uses: TostCorp/.github/workflows/codeql.yml@main
    with:
      language: csharp

  tag:
    permissions:
      contents: write
    uses: TostCorp/.github/workflows/git-tag.yml@main
    secrets: 
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      ref: ${{ github.event.pull_request.merge_commit_sha }}

  build:
    needs: tag
    permissions:
      contents: read
    uses: TostCorp/.github/workflows/dotnet-build.yml@main
    secrets: 
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_GITHUB_USERNAME: ${{ secrets.NUGET_GITHUB_USERNAME }}
    with:
      ref: ${{ github.event.pull_request.merge_commit_sha }}
      version: ${{ needs.tag.outputs.tag }}

  nuget-pack:
    needs: [ "tag", "build" ]
    permissions:
      contents: read
    uses: TostCorp/.github/workflows/nuget-pack.yml@main
    secrets: 
      AUTH_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_GITHUB_USERNAME: ${{ secrets.NUGET_GITHUB_USERNAME }}
    with:
      version: ${{ needs.tag.outputs.tag }}

  nuget-push-github:
    needs: [ "nuget-pack" ]
    permissions:
      packages: write
    uses: TostCorp/.github/workflows/nuget-push.yml@main
    secrets: 
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AUTH_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_GITHUB_USERNAME: ${{ secrets.NUGET_GITHUB_USERNAME }}

  nuget-push-nuget-org:
    needs: [ "nuget-pack" ]
    permissions:
      packages: write
    uses: TostCorp/.github/workflows/nuget-push.yml@main
    secrets: 
      AUTH_TOKEN: ${{ secrets.NUGET_ORG_TOKEN }}
      AUTH_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_GITHUB_USERNAME: ${{ secrets.NUGET_GITHUB_USERNAME }}
    with:
      nuget_server: "nuget.org"

  delete_prerelease_tags:
    needs: [ "nuget-pack" ]
    permissions:
      contents: write
    uses: TostCorp/.github/workflows/delete-prerelease-git-tags.yml@main
    with:
      ref: ${{ github.event.pull_request.merge_commit_sha }}
      branch_name: ${{ github.event.pull_request.head.ref }}
    secrets: 
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
